"""Integration tests for the pipeline with mocked LLM.

Uses unittest.mock to simulate LLM responses without making HTTP calls.
"""

import json
import pytest
from unittest.mock import patch
from pathlib import Path

from text_to_sql_flow.pipeline import run_generation, MAX_RETRIES

# A valid minimal flow JSON that the mock LLM returns
VALID_FLOW_JSON = json.dumps({
    "name": "MOCKED_FLOW",
    "description": "Generated by mocked LLM",
    "steps": [
        {
            "name": "MOCK_STEP",
            "parents": [],
            "order": 1,
            "sql": "SELECT 1",
            "output": {"tempView": "V_MOCK", "table": ""},
            "description": "",
            "diagram": {"x": 80, "y": 160},
            "active": True,
            "createdDate": {"$date": "2026-05-15T01:44:25.911Z"},
        }
    ],
})

BAD_JSON = "This is not valid JSON at all."


class TestPipelineSuccess:
    def test_run_generation_with_mock(self, tmp_path):
        """Pipeline returns a Path and creates output file."""
        with patch("text_to_sql_flow.pipeline.call_llm", return_value=VALID_FLOW_JSON):
            result = run_generation("test flow", tmp_path)
            assert isinstance(result, Path)
            assert result.exists()

    def test_run_generation_writes_correct_content(self, tmp_path):
        """Written file contains the expected flow name."""
        with patch("text_to_sql_flow.pipeline.call_llm", return_value=VALID_FLOW_JSON):
            result = run_generation("create a test flow", tmp_path)
            with open(result) as f:
                data = json.load(f)
            assert data["name"] == "MOCKED_FLOW"
            assert len(data["steps"]) == 1


class TestPipelineRetry:
    def test_run_generation_retries_on_bad_json(self, tmp_path):
        """Pipeline retries when LLM returns malformed JSON then succeeds."""
        mock_responses = [BAD_JSON, VALID_FLOW_JSON]
        with patch(
            "text_to_sql_flow.pipeline.call_llm",
            side_effect=mock_responses,
        ):
            result = run_generation("test flow", tmp_path)
            assert result.exists()
            with open(result) as f:
                data = json.load(f)
            assert data["name"] == "MOCKED_FLOW"

    def test_run_generation_fails_after_max_retries(self, tmp_path):
        """Pipeline raises RuntimeError after all retries exhausted."""
        with patch(
            "text_to_sql_flow.pipeline.call_llm",
            return_value=BAD_JSON,
        ):
            with pytest.raises(RuntimeError, match=f"after {MAX_RETRIES} retries"):
                run_generation("test flow", tmp_path)
